version: '3.9'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meditation
    ports: ["3306:3306"]
    command: --default-authentication-plugin=mysql_native_password
